apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-52
spec:
  replicas: 1
  selector:
   matchLabels:
    app: nginx-52
  template:
    metadata:
      labels:
        kubernetes.io/hostname: pod52-worker1
        app: nginx-52
    spec:
      containers:
      - name: nginx-52
        image: nginx:alpine
        ports:
        - containerPort: 80
