apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: blog-wp-rewrite
  namespace: default
spec:
  rules:
  - host: blog.robyyasiramri.com
    http:
      paths:
      - backend:
          serviceName: wordpress-robyyasiramri
          servicePort: 80
        path: /
